name: Server

on:
    push:
        branches: [main]

    workflow_dispatch:

jobs:
    push:
        name: Push
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Deploy
              uses: wlixcc/SFTP-Deploy-Action@v1.2.4
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  port: ${{ secrets.FTP_PORT }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  remote_path: "/"
                  sftp_only: true
